# Training parameters
model_single: {'model': 'single',
               'layers': [[1024, 1024, 1024, 1024], [512]]}

models: [model_single]

epochs: 15
batch_sizes: [128, 256, 512, 1024]
dropouts: [0] #0.0, 0.12, 0.25, 0.35]
gpus: [1]

