# Training parameters
model_single: {'model': 'single',
               'layers': [[512, 512, 512, 512], [512]]}

models: [model_single]

epochs: 10
batch_sizes: [32, 64, 128, 256, 512, 1024]
dropouts: [0] #0.0, 0.12, 0.25, 0.35]
gpus: [2, 1]

